variable "codepipeline_bucket_name" {}
variable "codebuild_project_name" {}
variable "codedeploy_app_name" {}
variable "codedeploy_deployment_group_name" {}
variable "codepipeline_name" {}
variable "ecs_cluster_name" {}
variable "ecs_service_name" {}
variable "git_full_repo_id" {}
variable "git_branch_name" {}
variable "ecs_asg_arn" {}
variable "alb_listener_blue_arn" {}
variable "alb_listener_green_arn" {}
variable "alb_tg_blue_name" {}
variable "alb_tg_green_name" {}
variable "ecr_repository_uri" {}
variable "container_name" {}
variable "container_port" {}
variable "ecs_task_definition_arn" {}